# Generated by Django 4.1.1 on 2022-10-20 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0008_alter_minutemeeting_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Página')),
                ('chapter', models.CharField(blank=True, max_length=7, null=True, verbose_name='Capítulo')),
                ('item', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item')),
                ('theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tema')),
                ('number_people_comented', models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Número de Pessoas que Comentaram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Leitura do Manual',
                'verbose_name_plural': 'Leituras dos Manuais',
            },
        ),
        migrations.CreateModel(
            name='ManualReadedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255, verbose_name='Nome da Pessoa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.manualreading')),
            ],
            options={
                'verbose_name': 'Manual lido por',
                'verbose_name_plural': 'Manuais lidos por',
            },
        ),
    ]
