# Generated by Django 4.1.1 on 2022-10-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreading',
            name='number_people_comented',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Pessoas que Comentaram'),
        ),
        migrations.AlterField(
            model_name='manualreading',
            name='page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Página'),
        ),
    ]
