# Generated by Django 4.1.1 on 2022-09-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(default=None, max_length=5, verbose_name='Código de Telefone do país'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='phone_code',
            field=models.CharField(default=None, max_length=5, verbose_name='Código de Telefone do Estado'),
            preserve_default=False,
        ),
    ]
