# Generated by Django 4.1.1 on 2022-09-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_remove_state_code_country_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='phone_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código de Telefone do Estado'),
        ),
    ]
