# Generated by Django 4.1.1 on 2022-09-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_state_phone_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='phone_code',
        ),
    ]
