# Generated by Django 4.1.1 on 2022-10-21 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0008_alter_minutemeeting_meeting'),
        ('members', '0008_alter_memberphone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invites', models.IntegerField(default=0, verbose_name='Total de Convites')),
                ('total_recruitments', models.IntegerField(default=0, verbose_name='Total de Recrutamentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Folha de Chamada',
                'verbose_name_plural': 'Folhas de Chamadas',
            },
        ),
        migrations.CreateModel(
            name='AttendenceSheetMemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status do Membro na Chamada',
                'verbose_name_plural': 'Status dos Membros nas Chamadas',
            },
        ),
        migrations.CreateModel(
            name='AttendenceSheetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invites_number', models.IntegerField(default=0, verbose_name='Número de Convites')),
                ('recruitments_number', models.IntegerField(default=0, verbose_name='Número de Recrutamentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendence_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendences.attendencesheet')),
                ('member_filiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberfiliation')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendences.attendencesheetmemberstatus')),
            ],
            options={
                'verbose_name': 'Membro na Chamada',
                'verbose_name_plural': 'Membros nas Chamadas',
            },
        ),
        migrations.AddConstraint(
            model_name='attendencesheetmember',
            constraint=models.UniqueConstraint(fields=('member_filiation', 'attendence_sheet'), name='unique_memberfiliation_in_attendencesheet'),
        ),
    ]
