# Generated by Django 4.1.1 on 2022-10-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('nickname', models.CharField(max_length=255, verbose_name='Apelido')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('deleted', models.BooleanField(default=False, verbose_name='Excluído?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
    ]
