# Generated by Django 4.1.1 on 2022-10-07 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_email_memberaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, choices=[('55', '+55 | Brazil')], default='001', max_length=3, null=True, verbose_name='Código do País')),
                ('prefix', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=9)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'Telefone do Membro',
                'verbose_name_plural': 'Telefoness dos Membros',
            },
        ),
    ]
