# Generated by Django 4.1.1 on 2022-10-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberfiliation_memberfiliationtype_postoffice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberfiliation',
            options={'verbose_name': 'Filiação do Membro', 'verbose_name_plural': 'Filiações dos Membros'},
        ),
        migrations.AlterModelOptions(
            name='memberfiliationtype',
            options={'verbose_name': 'Tipo do Membro', 'verbose_name_plural': 'Tipos dos Membros'},
        ),
        migrations.AlterModelOptions(
            name='postoffice',
            options={'verbose_name': 'Cargo de Oficial', 'verbose_name_plural': 'Cargos de Oficiais'},
        ),
        migrations.AlterModelOptions(
            name='postofficememberfiliation',
            options={'verbose_name': 'Cargo de Oficial do Membro na Organização', 'verbose_name_plural': 'Cargos de Oficiais dos Membros na Organizações'},
        ),
    ]
