# Generated by Django 4.1.1 on 2022-10-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_memberfiliation_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='memberfiliation',
            constraint=models.UniqueConstraint(fields=('member', 'organization'), name='unique_member_in_organization'),
        ),
        migrations.AddConstraint(
            model_name='postofficememberfiliation',
            constraint=models.UniqueConstraint(fields=('member_filiation', 'post_office'), name='unique_postoffice_to_memberfiliation'),
        ),
    ]
