# Generated by Django 4.1.1 on 2022-10-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_memberfiliation_unique_member_in_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberphone',
            options={'verbose_name': 'Telefone do Membro', 'verbose_name_plural': 'Telefones dos Membros'},
        ),
    ]
