# Generated by Django 4.1.1 on 2022-10-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_minutemeeting_description'),
        ('treasuries', '0002_alter_expense_options_alter_treasuryreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryreport',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião'),
        ),
        migrations.AddConstraint(
            model_name='treasuryreport',
            constraint=models.UniqueConstraint(fields=('meeting', 'date'), name='unique_report_for_meeting'),
        ),
    ]
