# Generated by Django 4.1.1 on 2022-09-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurLadyBlessedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('celebrate_date', models.DateField(verbose_name='Data de Comemoração')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Título de Nossa Senhora',
                'verbose_name_plural': 'Títulos de Nossa Senhora',
            },
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'verbose_name': 'Tipo de Organização', 'verbose_name_plural': 'Tipos de Organizações'},
        ),
    ]
