# Generated by Django 4.1.1 on 2022-10-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_ourladyblessedtitle_celebrate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateField(verbose_name='Data de Abertura')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Tipo de Organização')),
                ('organization_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organizationtype', verbose_name='Tipo de Organização')),
                ('our_blessed_lady_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.ourladyblessedtitle', verbose_name='Título de Nossa Senhora')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
    ]
