# Generated by Django 4.1.1 on 2022-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_organization_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaddress',
            name='linked_church',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Igreja Vinculada'),
        ),
    ]
