# Generated by Django 4.1.1 on 2022-10-03 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organizationaddress_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, choices=[('55', 'Brazil')], default='001', max_length=3, null=True, verbose_name='Código do País')),
                ('prefix', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=9)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Telefone do Cliente',
                'verbose_name_plural': 'Telefoness dos Clientes',
            },
        ),
    ]
