# Generated by Django 4.1.1 on 2022-10-05 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organizationphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaddress',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AlterField(
            model_name='organizationphone',
            name='country_code',
            field=models.CharField(blank=True, choices=[('55', '+55 | Brazil')], default='001', max_length=3, null=True, verbose_name='Código do País'),
        ),
    ]
