# Generated by Django 4.1.1 on 2022-11-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_alter_memberphone_options'),
        ('organizations', '0011_alter_organizationphone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Reunião')),
                ('start_at', models.TimeField(verbose_name='Início da Reunião')),
                ('reposition', models.BooleanField(default=False, verbose_name='Reposição')),
                ('place_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local da Reunião')),
                ('initial_prayer', models.BooleanField(default=True, verbose_name='Orações Iniciais')),
                ('rosary_prayer', models.BooleanField(default=True, verbose_name='Oração do Terço')),
                ('spiritual_read', models.CharField(blank=True, max_length=255, null=True, verbose_name='Leitura Espiritual')),
                ('standing_instructions_readed', models.BooleanField(default=False, verbose_name='Instrução Permanente')),
                ('catena_prayer', models.BooleanField(default=True, verbose_name='Oração da Catena')),
                ('allocutio', models.TextField(blank=True, null=True, verbose_name='Allocutio')),
                ('announcements', models.TextField(blank=True, null=True, verbose_name='Avisos e Outros Assuntos')),
                ('final_observations', models.TextField(blank=True, null=True, verbose_name='Observações Finais')),
                ('final_prayer', models.BooleanField(default=True, verbose_name='Orações Finais')),
                ('end_at', models.TimeField(verbose_name='Final da Reunião')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
            },
        ),
        migrations.CreateModel(
            name='MeetingMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_number', models.CharField(blank=True, max_length=7, null=True, verbose_name='Número da Ata')),
                ('description', models.TextField(default='### NÃO PREENCHIDA ###', verbose_name='Descrição completa da Ata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Ata da Reunião',
                'verbose_name_plural': 'Atas das Reuniões',
            },
        ),
        migrations.CreateModel(
            name='WelcomeGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='Nome do Convidado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
                ('welcome_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Membro Acolhedor')),
            ],
            options={
                'verbose_name': 'Convidado',
                'verbose_name_plural': 'Convidados',
            },
        ),
        migrations.CreateModel(
            name='MeetingOrganizationJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
                ('organization_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organização convidada')),
            ],
            options={
                'verbose_name': 'Reunião em Conjunto',
                'verbose_name_plural': 'Reuniões em Conjunto',
            },
        ),
        migrations.CreateModel(
            name='MeetingMinuteReaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_meeting_readed', to='meetings.meeting', verbose_name='Reunião em que foi lida')),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_readed', to='meetings.meetingminute', verbose_name='Ata Lida')),
            ],
            options={
                'verbose_name': 'Ata Lida de Reunião Anterior',
                'verbose_name_plural': 'Atas Lida de Reuniões Anteriores',
            },
        ),
    ]
