# Generated by Django 4.1.1 on 2022-11-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='orientations',
            field=models.TextField(blank=True, null=True, verbose_name='Orientações'),
        ),
    ]
