# Generated by Django 4.1.1 on 2022-12-05 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_templatetominutemeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminute',
            name='template_to_minute_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.templatetominutemeeting'),
        ),
    ]
