# Generated by Django 4.1.1 on 2022-10-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_organizationphone_options'),
        ('members', '0008_alter_memberphone_options'),
        ('meetings', '0003_meeting_reposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='Nome do Convidado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
                ('welcome_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Membro Acolhedor')),
            ],
            options={
                'verbose_name': 'Reunião em Conjunto',
                'verbose_name_plural': 'Reuniões em Conjunto',
            },
        ),
        migrations.CreateModel(
            name='MinuteMeetingReaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_meeting_readed', to='meetings.meeting', verbose_name='Reunião Lida')),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_readed', to='meetings.meeting', verbose_name='Ata Lida')),
            ],
            options={
                'verbose_name': 'Ata Lida de Reunião Anterior',
                'verbose_name_plural': 'Atas Lida de Reuniões Anteriores',
            },
        ),
        migrations.CreateModel(
            name='MinuteMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_number', models.CharField(blank=True, max_length=7, null=True, verbose_name='Número da Ata')),
                ('description', models.TextField(verbose_name='Descrição completa da Ata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Ata da Reunião',
                'verbose_name_plural': 'Atas das Reuniões',
            },
        ),
        migrations.CreateModel(
            name='MeetingOrganizationJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
                ('organization_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organização convidada')),
            ],
            options={
                'verbose_name': 'Reunião em Conjunto',
                'verbose_name_plural': 'Reuniões em Conjunto',
            },
        ),
    ]
