# Generated by Django 4.1.1 on 2022-12-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_organizationphone_options'),
        ('meetings', '0004_meetingminute_template_to_minute_meeting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateToMinuteMeeting',
            new_name='TemplateToMeetingMinute',
        ),
    ]
