# Generated by Django 4.1.1 on 2022-10-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_welcomeguest_minutemeetingreaded_minutemeeting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomeguest',
            options={'verbose_name': 'Convidado', 'verbose_name_plural': 'Convidados'},
        ),
        migrations.AlterField(
            model_name='minutemeetingreaded',
            name='minute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_readed', to='meetings.minutemeeting', verbose_name='Ata Lida'),
        ),
    ]
