# Generated by Django 4.1.1 on 2022-10-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_welcomeguest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='final_prayer',
            field=models.BooleanField(default=True, verbose_name='Orações Finais'),
        ),
        migrations.AlterField(
            model_name='minutemeetingreaded',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_meeting_readed', to='meetings.meeting', verbose_name='Reunião em que foi lida'),
        ),
    ]
