# Generated by Django 4.1.1 on 2022-10-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_minutemeeting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutemeeting',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião'),
        ),
    ]
