# Generated by Django 4.1.1 on 2022-11-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_alter_memberphone_options'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Código do Tipo de Participação')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do Tipo de Participação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Trabalho')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
            },
        ),
        migrations.CreateModel(
            name='WorkReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Código do Status do Relatório do Trabalho')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do Status do Relatório do Trabalho')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status do Relatório do Trabalho',
                'verbose_name_plural': 'Status dos Relatórios dos Trabalhos',
            },
        ),
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Folha de Trabalho | Trabalhos da Semana',
                'verbose_name_plural': 'Folhas de Trabalhos | Trabalhos das Semanas',
            },
        ),
        migrations.CreateModel(
            name='WorkSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Trabalho')),
                ('work_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.worksheet', verbose_name='Folha de Trabalhos')),
            ],
            options={
                'verbose_name': 'Item da Folha de Trabalho',
                'verbose_name_plural': 'Itens das Folhas de Trabalhos',
            },
        ),
        migrations.CreateModel(
            name='WorkSheetItemMemberFiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_filiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberfiliation', verbose_name='Membro')),
                ('participation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.participationtype', verbose_name='Tipo de Participação')),
                ('work_sheet_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.worksheetitem', verbose_name='Item da Folha de Trabalhos')),
            ],
            options={
                'verbose_name': 'Membro no Item da Folha de Trabalho',
                'verbose_name_plural': 'Membros nos Itens das Folhas de Trabalhos',
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_time', models.DurationField(verbose_name='Duração')),
                ('contacts_number', models.IntegerField(verbose_name='Contatos')),
                ('report_description', models.TextField(verbose_name='Relatório do Trabalho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='Reunião Reportada')),
                ('work_report_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.workreportstatus')),
                ('work_sheet_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='works.worksheetitem', verbose_name='Item da Folha de Trabalhos')),
            ],
            options={
                'verbose_name': 'Relatório de Trabalho',
                'verbose_name_plural': 'Relatórios de Trabalhos',
            },
        ),
        migrations.AddConstraint(
            model_name='worksheetitemmemberfiliation',
            constraint=models.UniqueConstraint(fields=('work_sheet_item', 'member_filiation'), name='unique_member_filiation_in_work_sheet_item'),
        ),
        migrations.AddConstraint(
            model_name='worksheetitem',
            constraint=models.UniqueConstraint(fields=('work_sheet', 'work'), name='unique_work_in_work_sheet'),
        ),
    ]
