# Generated by Django 4.1.1 on 2022-12-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_orientations'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='Reunião Reportada'),
        ),
    ]
