# Generated by Django 4.1.1 on 2022-10-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_alter_minutemeeting_meeting'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='Reunião Reportada'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='Reunião'),
        ),
    ]
